XCM Fee Handling
Polkadex-Substrate/parachain pull request #17
Opened 2023-02-17 12:55 UTC by zktony

2023-02-21 07:00 UTC, serhii-temchenko requested changes

2023-02-23 09:53 UTC, zktony commented on xcm-simulator/src/mock_amm.rs
> +		unimplemented!()
Just to satisfy the trait.

2023-02-23 09:53 UTC, zktony commented on xcm-simulator/src/mock_amm.rs
> +	}
Just to satisfy the trait.

2023-02-23 10:02 UTC, zktony commented on runtime/src/xcm_config.rs
> +		// Check if
removed

2023-02-23 10:02 UTC, zktony commented on runtime/src/xcm_config.rs
> +// where
removed

2023-02-23 10:11 UTC, Gauthamastro approved these changes

2023-02-23 10:52 UTC, serhii-temchenko approved these changes

2023-02-23 11:22 UTC, merged