Parachain upgraded to 0.9.32
Polkadex-Substrate/parachain pull request #2
Opened 2023-01-05 07:40 UTC by zktony

Parachain upgraded to 0.9.32

2023-01-07 17:00 UTC, serhii-temchenko requested changes

2023-01-07 17:00 UTC, serhii-temchenko commented on runtime/src/xcm_config.rs
> +// See issue #5233
Where this issue can be found?

2023-01-08 02:36 UTC, serhii-temchenko commented on node/Cargo.toml
> +try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
Found out that this wouldn't work as I assumed. If check [this](https://rust-lang.github.io/rfcs/2906-cargo-workspace-deduplicate.html#new-dependency-directives) section - it says:

> For now if a `workspace = true` dependency is specified then also specifying the `default-features` value is disallowed. The `default-features` value for a directive is inherited from the `[workspace.dependencies]` declaration, which defaults to true if nothing else is specified.

Plus I tried locally as well and received some circular deps error on build... But if I get it right - then we need to remove `default-feature` from the `runtime` crate [here](https://github.com/Polkadex-Substrate/parachain/blob/3621afaed8afcf378f69a89b7a78dc40506f6ef1/runtime/Cargo.toml#L18-L71)?
I'm about:

> ...specifying the `default-features` value is disallowed. ...

2023-01-09 10:33 UTC, zktony commented on node/src/chain_spec.rs
> +	let alice = get_account_id_from_seed::<sr25519::Public>("Alice");
Yeah .. I removed all warnings in #3

2023-01-10 03:56 UTC, serhii-temchenko commented on runtime/src/xcm_config.rs
> +// See issue #5233
Ok, I can see that this is a copy/paste from a different repo and used only for testing purpose but would be nice to have such things cleaned up...

2023-01-10 03:57 UTC, serhii-temchenko approved these changes

2023-01-10 05:45 UTC, Gauthamastro approved these changes

2023-01-10 05:45 UTC, merged