Added benchmarks for thea-council and xcm-helper
Polkadex-Substrate/parachain pull request #25
Opened 2023-04-05 08:32 UTC by zktony

Added benchmarks for thea-council and xcm-helper.

2023-04-05 12:04 UTC, 35359595 requested changes
please merge #26 and make all benchmarks running

2023-04-06 07:34 UTC, 35359595 requested changes

2023-04-06 07:34 UTC, 35359595 commented on pallets/xcm-helper/src/benchmarking.rs
> +		let boundec_vec:  BoundedVec<
max size of this vector is 10 so populate it to max capacity for worst case benchmarking.

2023-04-07 13:45 UTC, serhii-temchenko requested changes

2023-04-07 13:45 UTC, serhii-temchenko commented on pallets/xcm-helper/src/benchmarking.rs
`change_thea_key` extrinsic is not covered. Please add.

2023-05-15 04:46 UTC, Gauthamastro commented
Stale

2023-05-15 04:46 UTC, closed without merging