Updated Thea Pallet
Polkadex-Substrate/parachain pull request #59
Opened 2023-07-15 06:32 UTC by zktony

2023-07-19 10:02 UTC, serhii-temchenko requested changes
Please fix the CI errors.

2023-07-20 08:59 UTC, zktony commented on xcm-simulator/Cargo.toml
> +thea = { git = "https://github.com/Polkadex-Substrate/Polkadex.git", branch = "gj/on-chain-validation" }
done

2023-07-20 11:06 UTC, Gauthamastro approved these changes

2023-07-21 05:01 UTC, serhii-temchenko approved these changes

2023-07-21 05:02 UTC, merged