Integrated XToken Pallet in runtime
Polkadex-Substrate/parachain pull request #7
Opened 2023-01-20 12:43 UTC by zktony

* Integrated XToken Pallet in runtime.
* Added two new extrinsic in xcm_handler.
Will close #6

2023-01-25 22:39 UTC, serhii-temchenko requested changes

2023-01-25 22:39 UTC, serhii-temchenko commented on xcm-simulator/src/lib.rs
> +			println!("All events {:?}", System::events());
Please remove

2023-01-25 22:39 UTC, serhii-temchenko commented on xcm-simulator/src/lib.rs
> +		// TODO for R
Please extend todo info

2023-01-25 22:39 UTC, serhii-temchenko commented on xcm-simulator/src/lib.rs
> +			//pallet_balances::Pallet::<parachain::Runtime>::deposit_creating(&para_account_id(1), 1_000_000_000_000);
Please remove

2023-01-25 22:39 UTC, serhii-temchenko commented on xcm-simulator/src/parachain.rs
> +			//return Err(()) // Deny
Why is this commented out?

2023-02-02 05:47 UTC, zktony commented on xcm-simulator/src/parachain.rs
> +			//return Err(()) // Deny
done

2023-02-02 21:17 UTC, serhii-temchenko approved these changes

2023-02-07 05:15 UTC, merged