Integrated Thea Council
Polkadex-Substrate/parachain pull request #9
Opened 2023-02-01 12:36 UTC by zktony

Governance Pallet on Parachain:-
* Add a new member. (the bulk of current members or sudo user).
* Remove existing members. (majority of current members or sudo user).
* Delete malicious withdrawal requests. (Any member can do it).

XCM Handler Pallet:-
* Added withdrawal delay.
* Withdraw execution inside on_init function.

2023-02-02 00:01 UTC, serhii-temchenko commented
I it ready for review? If so - please add appropriate label

2023-02-04 12:55 UTC, serhii-temchenko requested changes

2023-02-04 12:55 UTC, serhii-temchenko commented on pallets/thea-council/src/tests.rs
> +// }
What this about?

2023-02-07 05:23 UTC, zktony commented on pallets/thea-council/src/lib.rs
> +		StorageOverflow,
done

2023-02-07 05:23 UTC, zktony commented on pallets/thea-council/src/tests.rs
> +// }
removed

2023-02-07 18:20 UTC, serhii-temchenko approved these changes

2023-02-08 05:43 UTC, Gauthamastro approved these changes

2023-02-08 05:43 UTC, merged